### ISSUE TITLE
Provisioning: Dashboard provider folderUid not working

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#140]
### What happened?

I'm using the panel 'Dashboard list', which previously, on version 10.1.1, had the option to select all folders. Now that I updated to the newest version (10.2.2), I need to specify a folder, which would be fine with me but now that I added the uid to my provisioned folder, it doesn't get set for the selected folder. Instead a random uid is assigned and since the dashboard is also privisioned, every time I restart grafana the default 'Dashboard' folder is selected instead of my own.

### What did you expect to happen?

Folder get's assigned defined uid and can be used in a provisioned dashboard.

### Did this work before?

Yes, at least until version 10.1.1. I checked, if the uid specified in the privisioning yaml get's assigned to the folder by selecting the folder instead of all in the 'Dashboard list' panel.

### How do we reproduce it?

1. Use the following yaml for the provisioning:

```yaml

apiVersion: 1

providers:

 - name: monitoring

 folder: 'Monitoring'

 folderUid: monitoring

 type: file

 options:

 path: /monitoring-dashboards/

```

2. Add the panel 'Dashboard list'

3. Select the folder 'Monitoring'

4. Look in the panel json and search for '"folderUID": '

5. See the random uid

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.2

OS: docker/kubernetes

Browser: chrome

### Grafana platform?

Docker
