### ISSUE TITLE
Can't connect to OpenSearch Datasource

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#286]
### What happened?

After migration to Grafana10 provisioned datasources has stoped working.

Example provisioned datasource

```

 ######################

 # Elasticsearch DB TEST #

 #######################

 - name: "elasticsearch-au-TEST"

 type: elasticsearch

 database: "[preview-]YYYY-MM-DD"

 url: "https://search-logs-hash.us-east-1.es.amazonaws.com/"

 jsonData:

 interval: Daily

 timeField: "time"

 esVersion: "8.0.0" # was 6.0.0 for Grafana8.5

 sigV4Auth: true

 sigV4AuthType: "default"

 sigV4Region: "us-east-1"

```

It's probably not related AWS IAM and network problems, because for version 8.5.* it working fine, with the similar IAM Role

### What did you expect to happen?

Able to connect to OpenSearch

### Did this work before?

Yes it works for 8.5.*

### How do we reproduce it?

1. Setup Grafana 10

2. Provision OpenSearch datasouce from config above

### Environment (with versions)?

Grafana: 10.3.1

OS: dockerhub - grafana/grafana

Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

OpenSearch
