### ISSUE TITLE
Provisioning/Alerting: Environment variable substitution not working for annotations

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#323]
### What happened?

Hi, 

we are working on enhancing our alerting right now and for this we want to use the environment variable substitution a bit more but have discovered that it is not working as expected.

We use currently env substitution for the labels in our alert files which is working.

But it looks like it is, for unknown reasons, not working when we try it in annotations which is unexpected.

We deploy our Grafana instance with Helm and use the provisioning path for setting up our alerts like this:

```

 extraConfigmapMounts:

 - name: grafana-alerts-provisioning

 subPath: ""

 mountPath: /etc/grafana/provisioning/alerting

 configMap: grafana-alerts

 readOnly: true

```

Below you can see that we have tested a few combinations for the annotations but in the screenshot you see its not rendered. 

But for the labels its working as expected.

### What did you expect to happen?

Environments variables are substituted in annotations in the same way as in labels.

### Did this work before?

no

### How do we reproduce it?

Alert file

```

apiVersion: 1

groups:

 - orgId: 1

 name: Kyverno

 folder: folder

 interval: 1m

 rules:

 - uid: 6pbn5054k

 title: Temporary role found

 condition: C

 data: ...

 noDataState: OK

 execErrState: Error

 for: 5m

 annotations:

 category: '{{ $labels.category }}'

 description: A temporary role was found

 policy: '{{ $labels.policy }}'

 severity: '{{ $labels.severity }}'

 summary: Temporary role found

 link: https://link.$AWS_REGION.$CLUSTER.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}

 link2: https://link.${AWS_REGION}.${CLUSTER}.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}

 link3: "https://link.${AWS_REGION}.${CLUSTER}.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}"

 link4: "https://link.$${AWS_REGION}.$${CLUSTER}.tld/#/cluster-policy-reports/kyverno?policies={{$labels.policy}}"

 labels:

 link: https://link.$AWS_REGION.$CLUSTER.tld/#/cluster-policy-reports/kyverno?policies={{$$labels.policy}}

 cluster: $CLUSTER

 level: error

 region: $REGION

 audiences: platform

 isPaused: false

```

Results in rendered label but not rendered in annotations

![image](https://github.com/grafana/grafana/assets/49561925/6c83fb0c-36fe-4864-8572-cbc2c2a52b3c)

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)

OS:

Browser:

### Grafana platform?

Kubernetes
